check the response code of the POST request

diff --git a/.github/workflows/cancel_testbench.yml b/.github/workflows/cancel_testbench.yml
--- a/.github/workflows/cancel_testbench.yml
+++ b/.github/workflows/cancel_testbench.yml
@@ -144,11 +144,18 @@ jobs:
               echo "On ${branch} at ${{ github.event.inputs.commit_sha }}: state=${state}"
               echo "Cancelling ${build_type}..."
               id=$(echo "${builds}" | jq -r '.build[0].id')
-              curl \
-                --request POST \
-                --header "Authorization: Bearer ${{ steps.retrieve-ksm-credentials.outputs.teamcity_token }}" \
-                --header "Accept: application/json" \
-                "${teamcity_builds}/id:${id}" \
-                -d '{"comment":"Cancel build from GitHub","readdIntoQueue":false}'
+              response_code=$(
+                curl \
+                  --request POST \
+                  --write-out "%{response_code}" \
+                  --header "Authorization: Bearer ${{ steps.retrieve-ksm-credentials.outputs.teamcity_token }}" \
+                  --header "Accept: application/json" \
+                  "${teamcity_builds}/id:${id}" \
+                  --data '{"comment":"Cancel build from GitHub", "readdIntoQueue":false}'
+              )
+              if [ "${response_code}" -ge 400 ]; then
+                echo "Cancellation failed. Request failed with status ${response_code}."
+                exit 1
+              fi
             fi
           done
